services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      SERVER_NAME: localhost
      DATABASE_URL: postgresql://app:password@database:5432/app?serverVersion=15&charset=utf8
      
  database:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: