services:
  app:
    container_name: app
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/frankenphp/Caddyfile
    working_dir: /app
    environment:
      SERVER_NAME: localhost
      DATABASE_URL: postgresql://app:password@database:5432/app?serverVersion=15&charset=utf8

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - database
            
  database:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: